version: '3.8'

services:
  db:
    image: postgres:14.3-alpine
    env_file: .env
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
  site_portfolio:
    build: .
    command:  python /usr/src/site_portfolio/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/site_portfolio
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - site_portfolio
    ports:
      - "80:80"
    volumes:
      - "./static/:/static"

volumes:
  postgres_data: